### ISSUE TITLE
chưa có xuất danh sách sv và check xem sv có đc đi thi hay ko

### ISSUE THREAD

**Issue by doanphungtu** [chituanh/BTVN-Java-HIT#7]
https://github.com/chituanh/BTVN-Java-HIT/blob/ab28b6d19249ed3b52f8d037074f72aa0407bc74/Week_5/Bai_1/src/Bai_3/Main.java#L1

**Comment by chituanh** [comment]
Cái nì em chưa kịp làm xong.........nó bị lỗi gì gì đó nó k cho em nhập
